/*
 * onejit - JIT compiler in C++
 *
 * Copyright (C) 2018-2021 Massimiliano Ghilardi
 *
 *     This Source Code Form is subject to the terms of the Mozilla Public
 *     License, v. 2.0. If a copy of the MPL was not distributed with this
 *     file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * code.hpp
 *
 *  Created on Jan 09, 2021
 *      Author Massimiliano Ghilardi
 */

#ifndef ONEJIT_CODE_HPP
#define ONEJIT_CODE_HPP

#include <onejit/fwd.hpp>
#include <onejit/imm.hpp>
#include <onejit/ir/node.hpp>
#include <onejit/type.hpp>
#include <onestl/buffer.hpp>

#include <cstdint> // uint32_t

namespace onejit {

class Code : private Buffer<CodeItem> {
  friend class Node;
  using T = CodeItem;
  using Base = Buffer<T>;

public:
  Code() noexcept;
  explicit Code(size_t capacity) noexcept;
  ~Code() noexcept;

  using Base::operator bool;

  // checked element access:
  // returns 0 if byte_offset is out of bounds
  T get(Offset byte_offset) const noexcept {
    return Base::operator[](byte_offset / sizeof(T));
  }

  // returns 0 if byte_offset is out of bounds
  int32_t int32(Offset byte_offset) const noexcept {
    return int32_t(get(byte_offset));
  }
  // returns 0 if byte_offset is out of bounds
  uint32_t uint32(Offset byte_offset) const noexcept {
    return get(byte_offset);
  }
  // returns 0 if byte_offset is out of bounds
  float float32(Offset byte_offset) const noexcept {
    return Float32Bits{get(byte_offset)}.val();
  }

  // returns 0 if byte_offset is out of bounds
  int64_t int64(Offset byte_offset) const noexcept {
    return int64_t(uint64(byte_offset));
  }
  // returns 0 if byte_offset is out of bounds
  uint64_t uint64(Offset byte_offset) const noexcept;
  // returns 0 if byte_offset is out of bounds
  double float64(Offset byte_offset) const noexcept {
    return Float64Bits{uint64(byte_offset)}.val();
  }

  Code &add_int32(int32_t i32) noexcept {
    return add_item(uint32_t(i32));
  }
  Code &add_uint32(uint32_t u32) noexcept {
    return add_item(u32);
  }
  Code &add_float32(float f32) noexcept {
    return add_item(Float32Bits{f32}.bits());
  }

  Code &add_int64(int64_t i64) noexcept {
    return add_uint64(uint64_t(i64));
  }
  Code &add_uint64(uint64_t u64) noexcept;
  Code &add_float64(double f64) noexcept {
    return add_uint64(Float64Bits{f64}.bits());
  }

  Code &add_item(CodeItem data) noexcept; // same as add_uint32()
  Code &add(CodeItems data) noexcept;
  Code &add(Header header) noexcept {
    return add_item(header.item());
  }
  Code &add(const Kind kind) noexcept;
  Code &add(const Kinds kinds) noexcept;
  Code &add(const Node &node, Offset parent_offset) noexcept;
  Code &add(View<char> chars) noexcept;

  // NODE_T must be a subclass of Node
  template <class NODE_T>
  ONEJIT_NOINLINE Code &add(const View<NODE_T> nodes, Offset parent_offset) noexcept {
    for (const Node &node : nodes) {
      if (!add(node, parent_offset)) {
        break;
      }
    }
    return *this;
  }

  Code &add_ranges(ChildRanges nodes, Offset parent_offset) noexcept;

  /// @return Code length, in CodeItems
  using Base::size;

  /// @return Code length, in bytes
  constexpr Offset length() const noexcept {
    return Base::size() * sizeof(T);
  }

  /// truncate Code to specified number of bytes
  Code &truncate(Offset length_bytes) noexcept {
    length_bytes /= sizeof(T);
    if (size_ > length_bytes) {
      size_ = length_bytes;
    }
    return *this;
  }

  /// truncate Code to zero user-generated bytes
  Code &clear() noexcept {
    Base::clearerr();
    return truncate(2 * sizeof(T));
  }

  constexpr const T *data() const noexcept {
    return Base::data();
  }
  constexpr const T *begin() const noexcept {
    return Base::begin();
  }
  constexpr const T *end() const noexcept {
    return Base::end();
  }

private:
  Code &init() noexcept;
};

} // namespace onejit

#endif // ONEJIT_CODE_HPP
